FROM docker/node-gyp:latest

RUN apk update && apk add nginx
RUN mkdir -p /run/nginx

COPY docker/nginx.conf /etc/nginx/nginx.conf
COPY docker/gd2_nginx.conf /etc/nginx/conf.d/gd2_nginx.conf
COPY frontend /opt/gd2/www

WORKDIR /opt/gd2/www
RUN npm install && npm run build

CMD ["nginx", "-g", "daemon off;"]
EXPOSE 8080 8443