# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: generic_data_display/data_sim/resources/data_definitions/protobuf/basic_protobuf.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='generic_data_display/data_sim/resources/data_definitions/protobuf/basic_protobuf.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nRtest_generic_data_display/resources/data_definitions/protobuf/basic_protobuf.proto\",\n\x0b\x45xampleData\x12\x0f\n\x07\x63ounter\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\tb\x06proto3'
)




_EXAMPLEDATA = _descriptor.Descriptor(
  name='ExampleData',
  full_name='ExampleData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='counter', full_name='ExampleData.counter', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date', full_name='ExampleData.date', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=130,
)

DESCRIPTOR.message_types_by_name['ExampleData'] = _EXAMPLEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExampleData = _reflection.GeneratedProtocolMessageType('ExampleData', (_message.Message,), {
  'DESCRIPTOR' : _EXAMPLEDATA,
  '__module__' : 'generic_data_display.data_sim.resources.data_definitions.protobuf.basic_protobuf_pb2'
  # @@protoc_insertion_point(class_scope:ExampleData)
  })
_sym_db.RegisterMessage(ExampleData)


# @@protoc_insertion_point(module_scope)
